#docker-compose.yml file is a configuration file used by Docker Compose to define and manage multi-container Docker applications.
#Automatically creates a network for the services to communicate with each other, simplifying inter-container communication.

# version: "3"
# services:
#   application:
#     build: .
#     image: ${IMAGE_NAME}
#     container_name: used_car_price_prediction_pj
#     ports:
#       - "8080:8080"


#docker-compose.yml file is a configuration file used by Docker Compose to define and manage multi-container Docker applications.
#Automatically creates a network for the services to communicate with each other, simplifying inter-container communication.
#building 2 images airflow & flaskapp

# version: "3"
# services:
#   airflow:
#     build:
#       context: ./
#       dockerfile: Dockerfile.airflow
#     image: airflowimage
#     container_name: used_car_price_prediction_airflow
#     ports:
#       - "8080:8080"

#   flaskapp:
#     build:
#       context: ./
#       dockerfile: Dockerfile.flask
    
#     image: flaskimage
#     container_name: used_car_price_prediction_flask
#     ports:
#       - "5000:5000"


# ======================

version: "3"
services:
  airflow:
    build:
      context: ./ 
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: used_car_price_prediction_airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW_ENV=production
    networks:
      - my_network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]  # Check if the web server is responding
      interval: 1m
      timeout: 10s
      retries: 3

  flaskapp:
    build:
      context: ./ 
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: used_car_price_prediction_flask
    ports:
      - "80:80"
    networks:
      - my_network
        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m
      timeout: 10s
      retries: 3

networks:
  my_network:
    driver: bridge